# Generated by Django 5.0.1 on 2026-03-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PipelineRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("stories_ingested", models.IntegerField(default=0)),
                ("stories_evaluated", models.IntegerField(default=0)),
                ("stories_assigned", models.IntegerField(default=0)),
                ("rewrites_generated", models.IntegerField(default=0)),
                ("error_log", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
