# Generated by Django 5.0.1 on 2026-03-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EditorialStyleSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "rules",
                    models.TextField(help_text="Global rules for the organization"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
