# Generated by Django 5.0.1 on 2026-03-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="editorialstylesheet",
            name="default_model",
            field=models.CharField(
                default="anthropic/claude-3-haiku",
                help_text="OpenRouter model ID",
                max_length=255,
            ),
        ),
    ]
