# Generated by Django 5.0.1 on 2026-03-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("bio", models.TextField(blank=True)),
                ("avatar_url", models.URLField(blank=True, null=True)),
                ("beat_description", models.TextField()),
                ("style_guide", models.TextField()),
                ("writing_voice", models.CharField(max_length=255)),
                ("tone_keywords", models.JSONField(blank=True, default=list)),
                (
                    "persona_prompt",
                    models.TextField(
                        help_text="Database-editable prompt for the rewrite engine"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
