# Generated by Django 5.0.1 on 2026-03-12 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("title", models.CharField(max_length=500)),
                ("url", models.URLField(unique=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("evaluated", "Evaluated"),
                            ("assigned", "Assigned"),
                            ("rewritten", "Rewritten"),
                            ("rejected", "Rejected"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("ai_score", models.FloatField(blank=True, null=True)),
                ("ai_rationale", models.TextField(blank=True, null=True)),
                ("topic_tags", models.JSONField(blank=True, default=list)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stories",
                        to="sources.source",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Stories",
            },
        ),
    ]
