# Generated by Django 5.0.1 on 2026-03-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="status",
            field=models.CharField(
                choices=[
                    ("ingested", "Ingested"),
                    ("evaluated", "Evaluated"),
                    ("assigned", "Assigned"),
                    ("rewritten", "Rewritten"),
                    ("rejected", "Rejected"),
                ],
                default="ingested",
                max_length=20,
            ),
        ),
    ]
