# Generated by Django 5.0.1 on 2026-03-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0003_alter_story_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
