# Generated by Django 5.0.1 on 2026-03-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[("rss", "RSS"), ("api", "API"), ("manual", "Manual")],
                        max_length=20,
                    ),
                ),
                ("feed_url", models.URLField(blank=True, null=True)),
                ("homepage_url", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
